title:  游戏程序员的自我修养
tagline:  探讨游戏开发的知识体系

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/neil3d'}
- {icon: 'twitter', link: 'https://twitter.com/neil3d'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/neil3d/'}
- {icon: 'envelope', link: 'mailto:neil3d@126.com'}
- {icon: 'rss-square', link: 'feed.xml'}
